# Generated by Django 3.2.25 on 2024-06-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='pedido_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Objeto Postado', 'Objeto Postado'), ('Em transferência', 'Em transferência'), ('Unidade de tratamento', 'Unidade de tratamento'), ('Em Rota de entrega', 'Em Rota de entrega'), ('Entregue', 'Entregue')], default='A Caminho', max_length=55),
        ),
    ]
