# Generated by Django 4.2.3 on 2024-06-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='id',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pedido_id',
            field=models.AutoField(default=1200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Entregue', 'Entregue'), ('A Caminho', 'A Caminho'), ('Cancelado', 'Cancelado')], default='A Caminho', max_length=10),
        ),
    ]
