services:
  app:
    container_name: app
    build: .
    #command: sh -c "python3 manage.py runserver 0.0.0.0:80"
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn --config appconsulta/gunicorn_conf.py appconsulta.wsgi:application"
    restart: always
    expose:
    #ports:
      - "8080:8080"
    #  - "80:80"
    volumes:
      - ./app:/app
      - /var/www/static/:/var/www/static/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/static/:/var/www/static/
      - /nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - app

  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /certbot/www/:/var/www/certbot/:rw
      - /certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx


    

     
    

     