services:
  app:
    container_name: app
    build: .
    #command: sh -c "python3 manage.py runserver 0.0.0.0:80"
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn --config appconsulta/gunicorn_conf.py appconsulta.wsgi:application"
    restart: always
    expose:
    #ports:
      - "8080:8080"
    #  - "80:80"
    volumes:
      - ./app:/app
      - ./app/static/:/var/www/static/
      - ./var/certbot/conf:/etc/letsencrypt/
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/static/:/var/www/static/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app

  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    command: certonly --webroot -w /var/www/certbot --force-renewal --email setenando87@gmail.com -d reastreieseupedidojdlg.online --agree-tos  
    depends_on:
      - nginx


    

     
    

     