services:
  app:
    build: .
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn --config appconsulta/gunicorn_conf.py appconsulta.wsgi:application"
    restart: always
    expose:
      - "8080"
    volumes:
      - ./app:/app
      - /var/www/static/:/var/www/static/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - /var/www/static/:/var/www/static/
       - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
       - app

  certbot:
     image: certbot/certbot:v1.15. # Updated to latest version for example (v1.15.)
     volumes_from:
       - nginx # Mount Nginx volume to Certbot container for certificate installation.
     depends_on:
       - nginx
     command: certonly --webroot --agree-tos --non-interactive \
               --email setenando87@gmail.com \
               --webroot-path=/usr/share/nginx/html \
               --domains reastreieseupedidojdlg.online,//www.reastreieseupedidojdlg.online # Update with your domain name(s)

